version: '3.8'

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8000:8000"
        env_file: .env
        environment:
          - TZ=America/Cuiaba
          - HOST=${HOST}
          - PORT=${PORT}
          - USER=${USER}
          - PASSWORD=${PASSWORD}
          - CATALOG=${CATALOG}
          - SCHEMA=${SCHEMA}